package Pygram.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Cluster_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Diagram_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Edge_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Node_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Provider_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new ProviderList_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new ResourceType_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716664L), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716669L), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716658L), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716610L), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71661eL), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71f089L), MetaIdFactory.conceptId(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71663bL)).seal();
}
