package Pygram.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCluster = createDescriptorForCluster();
  /*package*/ final ConceptDescriptor myConceptDiagram = createDescriptorForDiagram();
  /*package*/ final ConceptDescriptor myConceptEdge = createDescriptorForEdge();
  /*package*/ final ConceptDescriptor myConceptNode = createDescriptorForNode();
  /*package*/ final ConceptDescriptor myConceptProvider = createDescriptorForProvider();
  /*package*/ final ConceptDescriptor myConceptProviderList = createDescriptorForProviderList();
  /*package*/ final ConceptDescriptor myConceptResourceType = createDescriptorForResourceType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCluster, myConceptDiagram, myConceptEdge, myConceptNode, myConceptProvider, myConceptProviderList, myConceptResourceType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Cluster:
        return myConceptCluster;
      case LanguageConceptSwitch.Diagram:
        return myConceptDiagram;
      case LanguageConceptSwitch.Edge:
        return myConceptEdge;
      case LanguageConceptSwitch.Node:
        return myConceptNode;
      case LanguageConceptSwitch.Provider:
        return myConceptProvider;
      case LanguageConceptSwitch.ProviderList:
        return myConceptProviderList;
      case LanguageConceptSwitch.ResourceType:
        return myConceptResourceType;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCluster() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "Cluster", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716664L);
    b.class_(false, false, false);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755492");
    b.version(2);
    b.property("name", 0x3b3359bf7f716667L).type(PrimitiveTypeId.STRING).origin("4265851951061755495").done();
    b.aggregate("edges", 0x3b3359bf7f716665L).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716658L).optional(true).ordered(true).multiple(true).origin("4265851951061755493").done();
    b.alias("Cluster");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "Diagram", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716669L);
    b.class_(false, false, true);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755497");
    b.version(2);
    b.property("title", 0x3b3359bf7f71666aL).type(PrimitiveTypeId.STRING).origin("4265851951061755498").done();
    b.property("filename", 0x3b3359bf7f71666fL).type(PrimitiveTypeId.STRING).origin("4265851951061755503").done();
    b.property("format", 0x3b3359bf7f71666cL).type(PrimitiveTypeId.STRING).origin("4265851951061755500").done();
    b.property("show", 0x3b3359bf7f716678L).type(PrimitiveTypeId.BOOLEAN).origin("4265851951061755512").done();
    b.property("provider", 0x61c8bd6f54885c7fL).type(PrimitiveTypeId.STRING).origin("7046089902878383231").done();
    b.property("providerSource", 0x61c8bd6f54886ffdL).type(PrimitiveTypeId.STRING).origin("7046089902878388221").done();
    b.property("providerVersion", 0x61c8bd6f54887004L).type(PrimitiveTypeId.INTEGER).origin("7046089902878388228").done();
    b.aggregate("edges", 0x3b3359bf7f716673L).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716658L).optional(true).ordered(true).multiple(true).origin("4265851951061755507").done();
    b.aggregate("clusters", 0x3b3359bf7f716675L).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716664L).optional(true).ordered(true).multiple(true).origin("4265851951061755509").done();
    b.alias("Diagram");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEdge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "Edge", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716658L);
    b.class_(false, false, false);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755480");
    b.version(2);
    b.property("label", 0x3b3359bf7f716659L).type(PrimitiveTypeId.STRING).origin("4265851951061755481").done();
    b.property("color", 0x3b3359bf7f71665bL).type(PrimitiveTypeId.STRING).origin("4265851951061755483").done();
    b.property("style", 0x3b3359bf7f71665eL).type(PrimitiveTypeId.STRING).origin("4265851951061755486").done();
    b.aggregate("originNode", 0x4a1152048eed635dL).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716610L).optional(false).ordered(true).multiple(false).origin("5337137212942017373").done();
    b.aggregate("targetNodes", 0x4a1152048eed635fL).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716610L).optional(true).ordered(true).multiple(true).origin("5337137212942017375").done();
    b.alias("Edge");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "Node", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716610L);
    b.class_(false, false, false);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755408");
    b.version(2);
    b.property("name", 0x3b3359bf7f71661aL).type(PrimitiveTypeId.STRING).origin("4265851951061755418").done();
    b.alias("Node");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProvider() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "Provider", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71661eL);
    b.class_(false, false, false);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755422");
    b.version(2);
    b.property("fullname", 0x3b3359bf7f716639L).type(PrimitiveTypeId.STRING).origin("4265851951061755449").done();
    b.property("acronym", 0x3b3359bf7f730677L).type(PrimitiveTypeId.STRING).origin("4265851951061862007").done();
    b.aggregate("resourceType", 0x6f6d29c5e2c9da48L).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71663bL).optional(true).ordered(true).multiple(true).origin("8029119640561637960").done();
    b.alias("Provider");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProviderList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "ProviderList", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71f089L);
    b.class_(false, false, true);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061790857");
    b.version(2);
    b.aggregate("providers", 0x3b3359bf7f71f08aL).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71661eL).optional(true).ordered(true).multiple(true).origin("4265851951061790858").done();
    b.alias("Provider List");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForResourceType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Pygram", "ResourceType", 0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f71663bL);
    b.class_(false, false, false);
    b.origin("r:66d604ed-fb50-48df-ab7b-ae2ba1575adb(Pygram.structure)/4265851951061755451");
    b.version(2);
    b.property("type", 0x3b3359bf7f71663eL).type(PrimitiveTypeId.STRING).origin("4265851951061755454").done();
    b.aggregate("nodes", 0x3b3359bf7f716640L).target(0x1882bc4a84224af4L, 0xa4e0177f578ae42eL, 0x3b3359bf7f716610L).optional(true).ordered(true).multiple(true).origin("4265851951061755456").done();
    b.alias("ResourceType");
    return b.create();
  }
}
